// src/App.tsx
import React from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { BrowserRouter, Link, Route, Routes } from 'react-router-dom';
import { addToCart, removeFromCart } from './actions/actioncreators';
import './App.scss';
import logo from './assets/static/images/logo.png';
import Home from './components/Home/Home';
import Login from './components/Login/Login';
import Products from './components/Products/Products';
import Register from './components/Register/Register';
function App() {
  const store = useSelector((store: []) => store);
  console.log(store);

  return (
    <>
      <BrowserRouter>
        <nav className="navbar navbar-expand-lg navbar-light bg-light">
          <Link to={'/'} className="nav-link">
            <img className="navbar-brand" src={logo} alt="" />
          </Link>

          <button
            className="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarText"
            aria-controls="navbarText"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span className="navbar-toggler-icon"></span>
          </button>
          <div className="collapse navbar-collapse" id="navbarText">
            <div>
              <ul className="navbar-nav mr-auto">
                <li className="nav-item">
                  <Link to={'/home'} className="nav-link">
                    Home
                  </Link>
                </li>
                <li className="nav-item">
                  <Link to={'/home'} className="nav-link">
                    Products
                  </Link>
                </li>
              </ul>
            </div>
            <div>
              <div style={{ display: 'flex' }}>
                <Link to={'/'} className="nav-link">
                  <span style={{ fontSize: '12px' }}>SignIn</span>
                </Link>
                <Link to={'/register'} className="nav-link">
                  <span style={{ fontSize: '12px' }}>Register</span>
                </Link>
              </div>
              <button
                className="btn btn-primary"
                data-bs-toggle="modal"
                data-bs-target="#exampleModal"
                onClick={() => console.log(store)}
              >
                <i className="fas fa-shopping-cart"></i> {store.length} Items
              </button>
            </div>
          </div>
        </nav>

        <div
          className="modal fade"
          id="exampleModal"
          tabIndex={-1}
          aria-labelledby="exampleModalLabel"
          aria-hidden="true"
        >
          <div className="modal-dialog">
            <div className="modal-content">
              <div className="modal-header">
                <h5 className="modal-title" id="exampleModalLabel">
                  My Cart
                </h5>
                <button
                  type="button"
                  className="btn-close"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                ></button>
              </div>
              <div className="modal-body">{CartRender()}</div>
              <div className="modal-footer">
                <button
                  type="button"
                  className="btn btn-primary"
                  style={{
                    display: 'flex',
                    justifyContent: 'space-between',

                    width: '100%',
                  }}
                >
                  <span>Proceed to Checkout</span>
                  <span>Rs 100</span>
                </button>
              </div>
            </div>
          </div>
        </div>
        <Routes>
          <Route path="/" element={<Login />} />
          <Route path="/register" element={<Register />} />
          <Route path="/home" element={<Home />} />
          <Route path="/products" element={<Products />} />
          <Route path="/product/:id" element={<Products />} />
          {/* <Route path="/new-course" element={<NewCourse />} />
          <Route path="/post-details/:id" element={<PostDetails />} /> */}
          <Route
            path="*"
            element={
              <>
                <h1>Resource Not Found</h1>
              </>
            }
          />
        </Routes>
      </BrowserRouter>
      <div className="footer">
        Copyright 2011-2022 Sabka Bazaar Grocery Supplies Pvt Ltd.
      </div>
    </>
  );
}

function CartRender() {
  const dispatch = useDispatch();
  const store = useSelector((store: any[]) => store);
  const cartItems = Array.from(new Set(store)).map((item: any, index) => {
    return (
      <>
        <div
          style={{
            display: 'flex',
          }}
          key={index}
          className="my-2"
        >
          <img
            src={require(`../src/assets/static/images/products/${item.imageURL}`)}
            width="90px"
            height="90px"
            alt=""
          />
          <div>
            <h6 className="mx-3">{item.name}</h6>
            <div
              style={{
                display: 'flex',
              }}
            >
              <i
                className="fa-solid fa-circle-minus mx-3 my-1"
                onClick={() => dispatch(removeFromCart(item))}
              ></i>
              {store.filter((unique: any) => unique.id === item.id).length}
              <i
                className="fa-solid fa-circle-plus mx-3 my-1"
                onClick={() => dispatch(addToCart(item))}
              ></i>
              <span className="mx-3">x</span>
              <span className="mx-3">Rs.{item.price}</span>
            </div>
          </div>
          <div className="my-4 mx-5">
            Rs.
            {item.price *
              store.filter((unique: any) => unique.id === item.id).length}
          </div>
        </div>
      </>
    );
  });

  return (
    <div
      style={{
        display: 'flex',
        justifyContent: 'space-between',
        flexDirection: 'column',
      }}
    >
      {cartItems.length ? cartItems : <h3>No items</h3>}
    </div>
  );
}

export default App;

// src/app/app.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, OnInit, ViewEncapsulation } from '@angular/core';
import { Router } from '@angular/router';
import { BehaviorSubject, Observable, Subject } from 'rxjs';
import { AddToCartService } from './add-to-cart.service';
import { Categories, Products } from './home/home.interfaces';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class AppComponent implements OnInit {
  title = 'shopping-cart-assignment';
  products: any = {};
  cartItems: Products[][] = [];
  categories: Categories[] = [];

  constructor(
    private router: Router,
    private cartService: AddToCartService,
    private http: HttpClient
  ) {}
  ngOnInit(): void {
    this.cartService.products.subscribe((res) => {
      this.cartItems = [];
      res.forEach((item) => {
        if (!this.products[item.id] || !this.products[item.id].length) {
          this.products[item.id] = [];
        }
        (this.products[item.id] as Products[]).push(item);
      });

      for (const key in this.products) {
        if (Object.prototype.hasOwnProperty.call(this.products, key)) {
          const element = this.products[key];
          this.cartItems.push(element);
        }
      }
    });
    this.fetchCategories().subscribe((res) => {
      this.categories = res.sort((item) => item.order);
    });
  }

  navigateToLoginRegistration() {
    this.router.navigate(['/login-registration']);
  }

  navigateHome() {
    this.router.navigate(['/']);
  }

  fetchCategories(): Observable<Categories[]> {
    return this.http.get<Categories[]>(
      '../../assets/server/categories/index.get.json'
    );
  }

  navigateToCategory(key: string) {
    this.router.navigate(['/category', key]);
  }
}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img
        src="../assets/static/images/logo.png"
        height="60px"
        alt="Not found"
      />
    </a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="page"
            (click)="navigateHome()"
            >Home</a
          >
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Products
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li *ngFor="let item of categories" class="dropdown-item">
              <span (click)="navigateToCategory(item.id)"
                >{{ item.name }}
                <hr class="dropdown-divider"
              /></span>
            </li>
          </ul>
        </li>
      </ul>

      <ul class="navbar-nav">
        <li class="nav-item">
          <div>
            <button
              class="btn btn-light"
              (click)="navigateToLoginRegistration()"
            >
              SignIn
            </button>
            <button
              class="btn btn-light"
              (click)="navigateToLoginRegistration()"
            >
              Register
            </button>
          </div>
          <button
            type="button"
            class="btn btn-secondary"
            data-bs-toggle="modal"
            data-bs-target="#exampleModal"
          >
            <img src="../assets/static/images/cart.svg" alt="" srcset="" /><span
              >{{ cartItems.length }} Item</span
            >
          </button>
          <!-- Modal -->
          <div
            class="modal fade"
            id="exampleModal"
            tabindex="-1"
            aria-labelledby="exampleModalLabel"
            aria-hidden="true"
          >
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">
                    My Cart ({{ cartItems.length }} Item)
                  </h5>
                  <button
                    type="button"
                    class="btn-close btn-close-white"
                    data-bs-dismiss="modal"
                    aria-label="Close"
                  ></button>
                </div>
                <div class="modal-body">
                  <div *ngFor="let item of cartItems">
                    <div *ngIf="item.length" class="cart-item-align">
                      <img
                        class="vertical-align"
                        [src]="item[0].imageURL"
                        alt=""
                      />
                      <div class="vertical-align">
                        <h6>{{ item[0].name }}</h6>
                        <div>
                          <button class="btn" (click)="item.pop()">-</button>
                          {{ item.length }}
                          <button class="btn" (click)="item.push(item[0])">
                            +
                          </button>
                          <span> x {{ item[0].price }}</span>
                        </div>
                      </div>
                      <p class="vertical-align">
                        Rs.{{ item.length * item[0].price }}
                      </p>
                    </div>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-primary cart-button">
                    Proceed to checkout
                  </button>
                </div>
              </div>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="outlet">
  <div class="sidenav">
    <ul aria-labelledby="navbarDropdown">
      <li *ngFor="let item of categories" class="dropdown-item">
        <span (click)="navigateToCategory(item.id)">{{ item.name }} </span>
        <hr class="dropdown-divider" />
      </li>
    </ul>
  </div>
  <router-outlet></router-outlet>
</div>

<div class="footer">
  Copyright &copy; 2011-2022 Sabka Bazaar Grocery Supplies Pvt Ltd
</div>
