// src/app/home/home.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { forkJoin, Observable } from 'rxjs';
import { Banners, Categories, Products } from './home.interfaces';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss'],
})
export class HomeComponent implements OnInit {
  banners!: Banners[];
  categories!: Categories[];

  constructor(private http: HttpClient, private router: Router) {}

  ngOnInit(): void {
    forkJoin([this.fetchBanners(), this.fetchCategories()]).subscribe(
      (response) => {
        console.log(response);

        this.banners = response[0].sort((item) => item.order);
        this.categories = response[1].sort((item) => item.order);
      }
    );
  }

  fetchBanners(): Observable<Banners[]> {
    return this.http.get<Banners[]>(
      '../../assets/server/banners/index.get.json'
    );
  }

  fetchCategories(): Observable<Categories[]> {
    return this.http.get<Categories[]>(
      '../../assets/server/categories/index.get.json'
    );
  }

  navigateToCategory(key: string) {
    this.router.navigate(['/category', key]);
  }
}

<div class="home-align">
  <div
    id="carouselExampleIndicators"
    class="carousel slide"
    data-bs-ride="carousel"
  >
    <div class="carousel-indicators">
      <button
        type="button"
        data-bs-target="#carouselExampleIndicators"
        data-bs-slide-to="0"
        class="active"
        aria-current="true"
        aria-label="Slide 1"
      ></button>
      <button
        type="button"
        data-bs-target="#carouselExampleIndicators"
        data-bs-slide-to="0"
        class="active"
        aria-current="true"
        aria-label="Slide 1"
      ></button>
      <button
        type="button"
        data-bs-target="#carouselExampleIndicators"
        data-bs-slide-to="1"
        aria-label="Slide 2"
      ></button>
      <button
        type="button"
        data-bs-target="#carouselExampleIndicators"
        data-bs-slide-to="2"
        aria-label="Slide 3"
      ></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img
          class="d-block w-100"
          src="../../assets/static/images/offers/offer1.jpg"
          alt="First slide"
        />
      </div>
      <div class="carousel-item">
        <img
          class="d-block w-100"
          src="../../assets/static/images/offers/offer2.jpg"
          alt="Second slide"
        />
      </div>
      <div class="carousel-item">
        <img
          class="d-block w-100"
          src="../../assets/static/images/offers/offer2.jpg"
          alt="Third slide"
        />
      </div>
    </div>
    <button
      class="carousel-control-prev"
      type="button"
      data-bs-target="#carouselExampleIndicators"
      data-bs-slide="prev"
    >
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button
      class="carousel-control-next"
      type="button"
      data-bs-target="#carouselExampleIndicators"
      data-bs-slide="next"
    >
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

  <div *ngFor="let item of categories; index as i">
    <div
      *ngIf="item.enabled"
      [ngClass]="i % 2 == 0 ? 'categories-align' : 'categories-align-reverse'"
    >
      <img
        [src]="item.imageUrl"
        class="categories-image"
        alt="Not found"
        srcset=""
      />
      <span class="categories-description">
        <h5>{{ item.name }}</h5>
        <p>{{ item.description }}</p>
        <button class="btn" (click)="navigateToCategory(item.id)">
          Explore {{ item.key }}
        </button>
      </span>
    </div>
  </div>
</div>

// src/components/Home/Home.tsx
import axios from "axios";
import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import firstSlide from "../../assets/static/images/offers/offer1.jpg";
import secondSlide from "../../assets/static/images/offers/offer2.jpg";
import thirdSlide from "../../assets/static/images/offers/offer3.jpg";
import styles from "./Home.module.scss";

interface Categories {
  description: string;
  enabled: true;
  id: string;
  imageUrl: string;
  key: string;
  name: string;
  order: number;
}

function Home() {
  const [categoriesData, setCategoriesData] = useState<Categories[]>([]);
  const navigate = useNavigate();
  useEffect(() => {
    axios.get(`http://localhost:4200/categories`).then((response) => {
      console.log(response.data);
      setCategoriesData(response.data);
    });
  }, []);
  return (
    <>
      <div
        id="carouselExampleIndicators"
        className="carousel slide"
        data-bs-ride="carousel"
      >
        <div className="carousel-indicators">
          <button
            type="button"
            data-bs-target="#carouselExampleIndicators"
            data-bs-slide-to="0"
            className="active"
            aria-current="true"
            aria-label="Slide 1"
          ></button>
          <button
            type="button"
            data-bs-target="#carouselExampleIndicators"
            data-bs-slide-to="1"
            aria-label="Slide 2"
          ></button>
          <button
            type="button"
            data-bs-target="#carouselExampleIndicators"
            data-bs-slide-to="2"
            aria-label="Slide 3"
          ></button>
        </div>
        <div className="carousel-inner">
          <div className="carousel-item active">
            <img src={firstSlide} className="d-block w-100" alt="..." />
          </div>
          <div className="carousel-item">
            <img src={secondSlide} className="d-block w-100" alt="..." />
          </div>
          <div className="carousel-item">
            <img src={thirdSlide} className="d-block w-100" alt="..." />
          </div>
        </div>
        <button
          className="carousel-control-prev"
          type="button"
          data-bs-target="#carouselExampleIndicators"
          data-bs-slide="prev"
        >
          <span
            className="carousel-control-prev-icon"
            aria-hidden="true"
          ></span>
          <span className="visually-hidden">Previous</span>
        </button>
        <button
          className="carousel-control-next"
          type="button"
          data-bs-target="#carouselExampleIndicators"
          data-bs-slide="next"
        >
          <span
            className="carousel-control-next-icon"
            aria-hidden="true"
          ></span>
          <span className="visually-hidden">Next</span>
        </button>
      </div>
      <div>
        {categoriesData.length ? (
          categoriesData
            .filter((enabledCategory) => enabledCategory.enabled)
            .sort((sortedCategory) => sortedCategory.order)
            .map((category, index) => {
              console.log(category);

              return (
                <div
                  key={category.id}
                  className={`${styles.category} shadow-sm p-3 mb-5 bg-white rounded`}
                >
                  <img
                    src={require(`../../assets/static/images/category/${category.imageUrl}`)}
                    width="300px"
                    alt=""
                  />
                  <div className={styles.categoryCard}>
                    <h2>{category.name}</h2>
                    <p>{category.description}</p>
                    <button
                      className="btn"
                      onClick={() => navigate(`/product/${category.id}`)}
                    >
                      Explore {category.name}
                    </button>
                  </div>
                </div>
              );
            })
        ) : (
          <h2>Loading..</h2>
        )}
      </div>
    </>
  );
}
export default Home;
